"""initial schema

Revision ID: 350f178f172b
Revises: 
Create Date: 2026-08-08 06:02:00.682804

"""
from alembic import op
import sqlalchemy as sa


revision = '350f178f172b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caa_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_exposition_internet', sa.Float(), nullable=False),
    sa.Column('weight_exposition_dmz', sa.Float(), nullable=False),
    sa.Column('weight_exposition_internal', sa.Float(), nullable=False),
    sa.Column('weight_exposition_airgapped', sa.Float(), nullable=False),
    sa.Column('weight_criticite_critical', sa.Float(), nullable=False),
    sa.Column('weight_criticite_high', sa.Float(), nullable=False),
    sa.Column('weight_criticite_medium', sa.Float(), nullable=False),
    sa.Column('weight_criticite_low', sa.Float(), nullable=False),
    sa.Column('weight_exploitable', sa.Float(), nullable=False),
    sa.Column('normalization_divisor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('exposition', sa.String(length=50), nullable=False),
    sa.Column('criticite', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('grade_actif', sa.String(length=5), nullable=True),
    sa.Column('score_actif', sa.Float(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_decommissioned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=True)
    op.create_table('ownership_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('hostname_pattern', sa.String(length=255), nullable=True),
    sa.Column('os_pattern', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sle_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caa_config_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('CRITIQUE', 'HAUTE', 'MOYENNE', 'FAIBLE', name='severity'), nullable=False),
    sa.Column('caa_min', sa.Float(), nullable=False),
    sa.Column('caa_max', sa.Float(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caa_config_id'], ['caa_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('severity')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'TEAM_MANAGER', 'READONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('decommissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('decommissioned_at', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decommissioned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['decommissioned_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decommissions_hostname'), 'decommissions', ['hostname'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_match', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=True),
    sa.Column('hostname_pattern', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('confluence_link', sa.String(length=1000), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='exceptionstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('plugin_name', sa.String(length=500), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('ticket_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_actions_plugin_name'), 'remediation_actions', ['plugin_name'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_name'), 'scans', ['name'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=500), nullable=False),
    sa.Column('cve', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('cvss_version', sa.String(length=20), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('exploitable', sa.Boolean(), nullable=False),
    sa.Column('caa_score', sa.Float(), nullable=True),
    sa.Column('caa_severity', sa.Enum('CRITIQUE', 'HAUTE', 'MOYENNE', 'FAIBLE', name='severity'), nullable=True),
    sa.Column('sle_delay_days', sa.Integer(), nullable=True),
    sa.Column('sle_due_date', sa.Date(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REMEDIATED', 'EXCEPTION', 'DECOMMISSIONED', name='findingstatus'), nullable=False),
    sa.Column('remediation_comment', sa.Text(), nullable=True),
    sa.Column('ticket_ref', sa.String(length=255), nullable=True),
    sa.Column('exception_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_cve'), 'findings', ['cve'], unique=False)
    op.create_index(op.f('ix_findings_plugin_name'), 'findings', ['plugin_name'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('new_findings', sa.Integer(), nullable=False),
    sa.Column('updated_findings', sa.Integer(), nullable=False),
    sa.Column('resolved_findings', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_action_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['remediation_actions.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_action_findings_action_id'), 'remediation_action_findings', ['action_id'], unique=False)
    op.create_index(op.f('ix_remediation_action_findings_finding_id'), 'remediation_action_findings', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_action_findings_finding_id'), table_name='remediation_action_findings')
    op.drop_index(op.f('ix_remediation_action_findings_action_id'), table_name='remediation_action_findings')
    op.drop_table('remediation_action_findings')
    op.drop_table('import_history')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_plugin_name'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_name'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_remediation_actions_plugin_name'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_decommissions_hostname'), table_name='decommissions')
    op.drop_table('decommissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sle_rules')
    op.drop_table('ownership_rules')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('caa_configs')
    # ### end Alembic commands ###
