"""add scan_observations table

Revision ID: 7a7ddb0744c8
Revises: 350f178f172b
Create Date: 2026-08-08 11:36:46.225589

"""
from alembic import op
import sqlalchemy as sa


revision = '7a7ddb0744c8'
down_revision = '350f178f172b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_observations_finding_id'), 'scan_observations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_scan_observations_scan_id'), 'scan_observations', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_observations_scan_id'), table_name='scan_observations')
    op.drop_index(op.f('ix_scan_observations_finding_id'), table_name='scan_observations')
    op.drop_table('scan_observations')
    # ### end Alembic commands ###
